/* gen-credits.js - regenerate CREDITS.md from ecg-library/index.json.
 *
 * CC BY and CC BY-SA require naming the author, the license, and pointing at the
 * original. That obligation is per-image and the library changes, so the credit
 * file is generated rather than hand-maintained: edit index.json, run this.
 *
 *   node gen-credits.js
 */
var fs = require('fs');
var path = require('path');
var ROOT = __dirname;

var lib = JSON.parse(fs.readFileSync(path.join(ROOT, 'ecg-library', 'index.json'), 'utf8'));

var missing = lib.filter(function (x) { return !x.author || x.author === 'Unknown'; });
var flagged = lib.filter(function (x) { return x.label_note; });

function esc(s) { return String(s == null ? '' : s).replace(/\|/g, '\\|'); }
function lic(x) {
  return x.license_url ? '[' + esc(x.license) + '](' + x.license_url + ')' : esc(x.license || '');
}

var byCondition = {};
lib.forEach(function (x) { (byCondition[x.condition] = byCondition[x.condition] || []).push(x); });

var out = [];
out.push('# Credits and licenses');
out.push('');
out.push('The practice ECGs in this trainer are **synthetic** and generated by `ecg-engine.js`.');
out.push('They are original work and carry no third-party rights.');
out.push('');
out.push('The **reference library** images below are real ECGs from Wikimedia Commons,');
out.push('reproduced under the license named for each. Most are CC BY-SA, which requires');
out.push('that any onward reuse credit the author and keep the same license.');
out.push('If you are an author listed here and the attribution is wrong, please open an issue.');
out.push('');
out.push('Total: ' + lib.length + ' images.');
out.push('');

Object.keys(byCondition).sort().forEach(function (cond) {
  out.push('## ' + cond);
  out.push('');
  out.push('| File | Author | License | Source |');
  out.push('|---|---|---|---|');
  byCondition[cond].forEach(function (x) {
    out.push('| `' + esc(x.filename) + '` | ' + esc(x.author || 'Unknown') + ' | ' + lic(x) +
      ' | [Commons](' + x.source_url + ') |');
  });
  out.push('');
});

if (flagged.length) {
  out.push('## Notes on labelling');
  out.push('');
  out.push('Where the Commons source describes something different from the condition we file');
  out.push('the image under, that is recorded here rather than quietly ignored.');
  out.push('');
  flagged.forEach(function (x) {
    out.push('- `' + esc(x.filename) + '` (' + esc(x.condition) + '): ' + esc(x.label_note));
  });
  out.push('');
}

fs.writeFileSync(path.join(ROOT, 'CREDITS.md'), out.join('\n'));
console.log('wrote CREDITS.md (' + lib.length + ' images, ' + Object.keys(byCondition).length + ' conditions)');
if (missing.length) {
  console.warn('WARNING: ' + missing.length + ' image(s) still lack an author: ' +
    missing.map(function (x) { return x.filename; }).join(', '));
  process.exitCode = 1;
}
